CREATE DATABASE IF NOT EXISTS minicurso
  DEFAULT CHARACTER SET utf8mb4;

USE minicurso;

CREATE TABLE IF NOT EXISTS contatos (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  nome       VARCHAR(120) NOT NULL,
  email      VARCHAR(180) NOT NULL,
  mensagem   TEXT NOT NULL,
  ip         VARCHAR(45) NULL,
  criado_em  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
